// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'bread_list_data.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

BreadListData _$BreadListDataFromJson(Map<String, dynamic> json) {
  return BreadListData(
    affenpinscher:
        (json['affenpinscher'] as List)?.map((e) => e as String)?.toList(),
    african: (json['african'] as List)?.map((e) => e as String)?.toList(),
    airedale: (json['airedale'] as List)?.map((e) => e as String)?.toList(),
    akita: (json['akita'] as List)?.map((e) => e as String)?.toList(),
    appenzeller:
        (json['appenzeller'] as List)?.map((e) => e as String)?.toList(),
    australian: (json['australian'] as List)?.map((e) => e as String)?.toList(),
    basenji: (json['basenji'] as List)?.map((e) => e as String)?.toList(),
    beagle: (json['beagle'] as List)?.map((e) => e as String)?.toList(),
    bluetick: (json['bluetick'] as List)?.map((e) => e as String)?.toList(),
    borzoi: (json['borzoi'] as List)?.map((e) => e as String)?.toList(),
    bouvier: (json['bouvier'] as List)?.map((e) => e as String)?.toList(),
    boxer: (json['boxer'] as List)?.map((e) => e as String)?.toList(),
    brabancon: (json['brabancon'] as List)?.map((e) => e as String)?.toList(),
    briard: (json['briard'] as List)?.map((e) => e as String)?.toList(),
    buhund: (json['buhund'] as List)?.map((e) => e as String)?.toList(),
    bulldog: (json['bulldog'] as List)?.map((e) => e as String)?.toList(),
    bullterrier:
        (json['bullterrier'] as List)?.map((e) => e as String)?.toList(),
    cairn: (json['cairn'] as List)?.map((e) => e as String)?.toList(),
    cattledog: (json['cattledog'] as List)?.map((e) => e as String)?.toList(),
    chihuahua: (json['chihuahua'] as List)?.map((e) => e as String)?.toList(),
    chow: (json['chow'] as List)?.map((e) => e as String)?.toList(),
    clumber: (json['clumber'] as List)?.map((e) => e as String)?.toList(),
    cockapoo: (json['cockapoo'] as List)?.map((e) => e as String)?.toList(),
    collie: (json['collie'] as List)?.map((e) => e as String)?.toList(),
    coonhound: (json['coonhound'] as List)?.map((e) => e as String)?.toList(),
    corgi: (json['corgi'] as List)?.map((e) => e as String)?.toList(),
    cotondetulear:
        (json['cotondetulear'] as List)?.map((e) => e as String)?.toList(),
    dachshund: (json['dachshund'] as List)?.map((e) => e as String)?.toList(),
    dalmatian: (json['dalmatian'] as List)?.map((e) => e as String)?.toList(),
    dane: (json['dane'] as List)?.map((e) => e as String)?.toList(),
    deerhound: (json['deerhound'] as List)?.map((e) => e as String)?.toList(),
    dhole: (json['dhole'] as List)?.map((e) => e as String)?.toList(),
    dingo: (json['dingo'] as List)?.map((e) => e as String)?.toList(),
    doberman: (json['doberman'] as List)?.map((e) => e as String)?.toList(),
    elkhound: (json['elkhound'] as List)?.map((e) => e as String)?.toList(),
    entlebucher:
        (json['entlebucher'] as List)?.map((e) => e as String)?.toList(),
    eskimo: (json['eskimo'] as List)?.map((e) => e as String)?.toList(),
    finnish: (json['finnish'] as List)?.map((e) => e as String)?.toList(),
    frise: (json['frise'] as List)?.map((e) => e as String)?.toList(),
    germanshepherd:
        (json['germanshepherd'] as List)?.map((e) => e as String)?.toList(),
    greyhound: (json['greyhound'] as List)?.map((e) => e as String)?.toList(),
    groenendael:
        (json['groenendael'] as List)?.map((e) => e as String)?.toList(),
    havanese: (json['havanese'] as List)?.map((e) => e as String)?.toList(),
    hound: (json['hound'] as List)?.map((e) => e as String)?.toList(),
    husky: (json['husky'] as List)?.map((e) => e as String)?.toList(),
    keeshond: (json['keeshond'] as List)?.map((e) => e as String)?.toList(),
    kelpie: (json['kelpie'] as List)?.map((e) => e as String)?.toList(),
    komondor: (json['komondor'] as List)?.map((e) => e as String)?.toList(),
    kuvasz: (json['kuvasz'] as List)?.map((e) => e as String)?.toList(),
    labrador: (json['labrador'] as List)?.map((e) => e as String)?.toList(),
    leonberg: (json['leonberg'] as List)?.map((e) => e as String)?.toList(),
    lhasa: (json['lhasa'] as List)?.map((e) => e as String)?.toList(),
    malamute: (json['malamute'] as List)?.map((e) => e as String)?.toList(),
    malinois: (json['malinois'] as List)?.map((e) => e as String)?.toList(),
    maltese: (json['maltese'] as List)?.map((e) => e as String)?.toList(),
    mastiff: (json['mastiff'] as List)?.map((e) => e as String)?.toList(),
    mexicanhairless:
        (json['mexicanhairless'] as List)?.map((e) => e as String)?.toList(),
    mix: (json['mix'] as List)?.map((e) => e as String)?.toList(),
    mountain: (json['mountain'] as List)?.map((e) => e as String)?.toList(),
    newfoundland:
        (json['newfoundland'] as List)?.map((e) => e as String)?.toList(),
    otterhound: (json['otterhound'] as List)?.map((e) => e as String)?.toList(),
    ovcharka: (json['ovcharka'] as List)?.map((e) => e as String)?.toList(),
    papillon: (json['papillon'] as List)?.map((e) => e as String)?.toList(),
    pekinese: (json['pekinese'] as List)?.map((e) => e as String)?.toList(),
    pembroke: (json['pembroke'] as List)?.map((e) => e as String)?.toList(),
    pinscher: (json['pinscher'] as List)?.map((e) => e as String)?.toList(),
    pitbull: (json['pitbull'] as List)?.map((e) => e as String)?.toList(),
    pointer: (json['pointer'] as List)?.map((e) => e as String)?.toList(),
    pomeranian: (json['pomeranian'] as List)?.map((e) => e as String)?.toList(),
    poodle: (json['poodle'] as List)?.map((e) => e as String)?.toList(),
    pug: (json['pug'] as List)?.map((e) => e as String)?.toList(),
    puggle: (json['puggle'] as List)?.map((e) => e as String)?.toList(),
    pyrenees: (json['pyrenees'] as List)?.map((e) => e as String)?.toList(),
    redbone: (json['redbone'] as List)?.map((e) => e as String)?.toList(),
    retriever: (json['retriever'] as List)?.map((e) => e as String)?.toList(),
    ridgeback: (json['ridgeback'] as List)?.map((e) => e as String)?.toList(),
    rottweiler: (json['rottweiler'] as List)?.map((e) => e as String)?.toList(),
    saluki: (json['saluki'] as List)?.map((e) => e as String)?.toList(),
    samoyed: (json['samoyed'] as List)?.map((e) => e as String)?.toList(),
    schipperke: (json['schipperke'] as List)?.map((e) => e as String)?.toList(),
    schnauzer: (json['schnauzer'] as List)?.map((e) => e as String)?.toList(),
    setter: (json['setter'] as List)?.map((e) => e as String)?.toList(),
    sheepdog: (json['sheepdog'] as List)?.map((e) => e as String)?.toList(),
    shiba: (json['shiba'] as List)?.map((e) => e as String)?.toList(),
    shihtzu: (json['shihtzu'] as List)?.map((e) => e as String)?.toList(),
    spaniel: (json['spaniel'] as List)?.map((e) => e as String)?.toList(),
    springer: (json['springer'] as List)?.map((e) => e as String)?.toList(),
    stbernard: (json['stbernard'] as List)?.map((e) => e as String)?.toList(),
    terrier: (json['terrier'] as List)?.map((e) => e as String)?.toList(),
    vizsla: (json['vizsla'] as List)?.map((e) => e as String)?.toList(),
    waterdog: (json['waterdog'] as List)?.map((e) => e as String)?.toList(),
    weimaraner: (json['weimaraner'] as List)?.map((e) => e as String)?.toList(),
    whippet: (json['whippet'] as List)?.map((e) => e as String)?.toList(),
    wolfhound: (json['wolfhound'] as List)?.map((e) => e as String)?.toList(),
  );
}

Map<String, dynamic> _$BreadListDataToJson(BreadListData instance) =>
    <String, dynamic>{
      'affenpinscher': instance.affenpinscher,
      'african': instance.african,
      'airedale': instance.airedale,
      'akita': instance.akita,
      'appenzeller': instance.appenzeller,
      'australian': instance.australian,
      'basenji': instance.basenji,
      'beagle': instance.beagle,
      'bluetick': instance.bluetick,
      'borzoi': instance.borzoi,
      'bouvier': instance.bouvier,
      'boxer': instance.boxer,
      'brabancon': instance.brabancon,
      'briard': instance.briard,
      'buhund': instance.buhund,
      'bulldog': instance.bulldog,
      'bullterrier': instance.bullterrier,
      'cairn': instance.cairn,
      'cattledog': instance.cattledog,
      'chihuahua': instance.chihuahua,
      'chow': instance.chow,
      'clumber': instance.clumber,
      'cockapoo': instance.cockapoo,
      'collie': instance.collie,
      'coonhound': instance.coonhound,
      'corgi': instance.corgi,
      'cotondetulear': instance.cotondetulear,
      'dachshund': instance.dachshund,
      'dalmatian': instance.dalmatian,
      'dane': instance.dane,
      'deerhound': instance.deerhound,
      'dhole': instance.dhole,
      'dingo': instance.dingo,
      'doberman': instance.doberman,
      'elkhound': instance.elkhound,
      'entlebucher': instance.entlebucher,
      'eskimo': instance.eskimo,
      'finnish': instance.finnish,
      'frise': instance.frise,
      'germanshepherd': instance.germanshepherd,
      'greyhound': instance.greyhound,
      'groenendael': instance.groenendael,
      'havanese': instance.havanese,
      'hound': instance.hound,
      'husky': instance.husky,
      'keeshond': instance.keeshond,
      'kelpie': instance.kelpie,
      'komondor': instance.komondor,
      'kuvasz': instance.kuvasz,
      'labrador': instance.labrador,
      'leonberg': instance.leonberg,
      'lhasa': instance.lhasa,
      'malamute': instance.malamute,
      'malinois': instance.malinois,
      'maltese': instance.maltese,
      'mastiff': instance.mastiff,
      'mexicanhairless': instance.mexicanhairless,
      'mix': instance.mix,
      'mountain': instance.mountain,
      'newfoundland': instance.newfoundland,
      'otterhound': instance.otterhound,
      'ovcharka': instance.ovcharka,
      'papillon': instance.papillon,
      'pekinese': instance.pekinese,
      'pembroke': instance.pembroke,
      'pinscher': instance.pinscher,
      'pitbull': instance.pitbull,
      'pointer': instance.pointer,
      'pomeranian': instance.pomeranian,
      'poodle': instance.poodle,
      'pug': instance.pug,
      'puggle': instance.puggle,
      'pyrenees': instance.pyrenees,
      'redbone': instance.redbone,
      'retriever': instance.retriever,
      'ridgeback': instance.ridgeback,
      'rottweiler': instance.rottweiler,
      'saluki': instance.saluki,
      'samoyed': instance.samoyed,
      'schipperke': instance.schipperke,
      'schnauzer': instance.schnauzer,
      'setter': instance.setter,
      'sheepdog': instance.sheepdog,
      'shiba': instance.shiba,
      'shihtzu': instance.shihtzu,
      'spaniel': instance.spaniel,
      'springer': instance.springer,
      'stbernard': instance.stbernard,
      'terrier': instance.terrier,
      'vizsla': instance.vizsla,
      'waterdog': instance.waterdog,
      'weimaraner': instance.weimaraner,
      'whippet': instance.whippet,
      'wolfhound': instance.wolfhound,
    };
